version: 1.0.0.2.{build}
configuration: Release
build:
  project: pdbdownloader_v15.sln
  verbosity: minimal
after_build:
- cmd: >-
    mkdir bin

    copy pdbdownloader\bin\Release\pdbdownloader.exe bin\pdbdownloader.exe

    7z a -tzip pdbdownloader.zip bin\*
artifacts:
- path: pdbdownloader.zip
  name: pdbdownloader.zip
deploy:
- provider: GitHub
  auth_token:
    secure: 3gx7eB6yX/XkzM1PW4XWkci1cNPIjwoY1+VnDlXuM93h45FXtahZQfhfiaOhIUAl
  artifact: pdbdownloader.zip
  draft: true
